### ISSUE TITLE
react not defined

### ISSUE THREAD

**Issue by joe-lz** [matfish2/vue-pagination-2#1]
- Vue.js version:2
- webpack
- FULL error message (including stack trace):
  vue.js?11b0:2574 [Vue warn]: Error when rendering component <pagination>: 
  vue.js?11b0:2217 Uncaught ReferenceError: React is not defined(…)
- relevant code:
- steps for reproducing the issue:

**Comment by matfish2** [comment]
This means that the jsx-transformer didn't work.
See
https://github.com/matfish2/vue-tables-2/issues/2. my last comment
on how to set it properly
