### ISSUE TITLE
NPM Install doesn't pull everything from the repository

### ISSUE THREAD

**Issue by trevorlasn** [matfish2/vue-pagination-2#11]
- Vue.js version: 2.1.8
- consumed using: (browserify/webpack) webpack mix(laravel)
- FULL error message (including stack trace): http://d.pr/i/10ahn/25d8SuL2
- relevant code: 

- steps for reproducing the issue: 

npm i --save vue-pagination-2  and look into node_modules/vue-pagination-2 and there is no /src, I had to manually clone the repo to node_modules/

Is this only me or it's a bug? Sorry for half-assed git issue, been fighting with this issue all afternoon.  I managed to solve this issue for local development but docker npm install produces the same bug.

**Comment by trevorlasn** [comment]
my package.json 

```bash
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-helper-vue-jsx-merge-props": "^2.0.2",
    "babel-loader": "^6.2.7",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-vue-jsx": "^3.1.2",
    "babel-preset-es2015": "^6.18.0",
    "bootstrap-sass": "^3.3.7",
    "eslint": "^3.11.1",
    "eslint-plugin-html": "^1.7.0",
    "gulp": "^3.9.1",
    "inject-loader": "^2.0.1",
    "install": "^0.8.4",
    "jasmine-core": "^2.5.2",
    "jquery": "^3.1.0",
    "json-loader": "^0.5.4",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sinon": "^1.0.5",
    "karma-webpack": "^1.8.0",
    "laravel-elixir": "^6.0.0-11",
    "laravel-elixir-browsersync-official": "^1.0.0",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "libphonenumber-js": "^0.2.27",
    "lodash": "^4.16.2",
    "npm": "^4.4.0",
    "sinon": "^1.17.7",
    "vue": "^2.1.8",
    "vue-pagination-2": "^0.2.4",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.3",
    "vue-tables-2": "^0.2.4",
    "vue-template-compiler": "^2.1.10",
    "vuejs-datepicker": "^0.4.20",
    "vuex": "^2.1.1"
  },
  "dependencies": {
    "path": "^0.12.7",
    "vue-style-loader": "^2.0.3"
  }
}
```

**Comment by matfish2** [comment]
The `src` folder was omitted by design, since the package is using the compiled version under the `compiled` folder. I see that the error you are getting is not from the pagination plugin but from `vue-tables-2`. I think the problem is that you have an old version of `vue-tables-2` coupled with the new version of `vue-pagination-2`. Please update and see if the problem persists.

**Comment by trevorlasn** [comment]
Update:


I updated the vue-tables-2 to the latest version and it works now.  Bravo!
