### ISSUE TITLE
Can you make a jsFiddle example

### ISSUE THREAD

**Issue by ncross42** [matfish2/vue-pagination-2#12]
- Vue.js version: 2.2.1
- consumed using: (browserify/webpack) : webpack
- FULL error message (including stack trace): nothing
- relevant code: nothing
- steps for reproducing the issue: nothing

Can you make a jsFiddle example?
I cannot run this component.

**Comment by matfish2** [comment]
I can't make a fiddle because there is no precompiled version. What exactly is the problem?

**Comment by GoBrianGo** [comment]
I don't understand how to use after reading your usage,and there is an error in my examply.
error msg: 'Failed to mount component: template or render function not defined. '

**Comment by ergonomicus** [comment]
Yes, fiddle would be useful.

**Comment by CaptainHypertext** [comment]
A demo (or at least a screenshot) would be super useful, otherwise I have to install, register, and test it just to see what it looks like.
