### ISSUE TITLE
[vuex] already installed. Vue.use(Vuex) should be called only once.

### ISSUE THREAD

**Issue by defaye** [matfish2/vue-pagination-2#13]
- Vue.js version: `2`
- consumed using: webpack
- FULL error message (including stack trace):
```
[vuex] already installed. Vue.use(Vuex) should be called only once.
install @ vuex.esm.js?edaa:668
Be.e.use @ vue.min.js:6
(anonymous) @ app.js?8b67:27
(anonymous) @ app-d224dac622.js:407
__webpack_require__ @ app-d224dac622.js:20
(anonymous) @ app-d224dac622.js:64
(anonymous) @ app-d224dac622.js:67
```

- relevant code:
```
import Vuex from 'vuex';
import { VuePagination, VueEvent } from 'vue-pagination-2';

Vue.use(Vuex);
Vue.use(VuePagination);
```
- steps for reproducing the issue:
In a Laravel 5.4 project, in `resources/assets/js/app.js` I have declared the above. Everything works if I comment out `Vue.use(Vuex);`.

**Comment by suguoyao** [comment]
+1! How can I fix this problem?

**Comment by matfish2** [comment]
I have no reference to vuex in my code other then registering a module. 
I was unable to reproduce this problem.
