### ISSUE TITLE
Number format the page and record numbers

### ISSUE THREAD

**Issue by grepsr** [matfish2/vue-pagination-2#15]
There seems to be no way to number format (add commas etc) to record numbers. Is this possible?

**Comment by matfish2** [comment]
I suppose I can add commas. Other than that what other format can the be applicable?

**Comment by grepsr** [comment]
Yeah, just adding number format with commas should suffice. Perhaps there needs to be an option for that, because while most people would want it number formatted with commas, some might not?

This should only happen for record numbers I think. Thanks!
