### ISSUE TITLE
Support custom template

### ISSUE THREAD

**Issue by pschaub** [matfish2/vue-pagination-2#16]
The vue-tables-2 supports custom templates. I want to change the styling of the complete table to support UIKit instead of Bootstrap. For this I need to customize all classes including all classes in the pagination.

So please add support for custom templates in vue-pagination-2 and please add in the documentation how to use it.

**Comment by KOMKZ** [comment]
same to upper, I found there aren't any customed paramaters in source.
vue-pagination-2 / template.js like following:
```
var template = require('./template.js');
var bus = require('./bus');

module.exports = {
  render: template()
}
```

**Comment by jim8786453** [comment]
Yep I'm also using Bootstrap 4 and I think the current template is 3, so this would be good for me too.

**Comment by matfish2** [comment]
Since this component is not registered as a plugin using `Vue.use` - unlike `vue-tables-2` - I cannot offer such functionality, i.e substitute the template with a user-supplied one.
However, the following should work (I haven't tested it):

A. Grab the content of `compiled/template.js`.
B. Modify it to your needs, but be careful not to mess with the functionality.
C. Merge it like so:

```js
import merge from 'merge';
import {Pagination} from 'vue-pagination-2'
import myTemplate from './path/to/template';
Pagination = merge(Pagination, {render:myTemplate()});
```

**Comment by jim8786453** [comment]
Thanks for your suggestion, I'm happy to go with that and I've given it a go but run into a bunch of issues that suggest I'm doing something stupid? In summary:

```
'Pagination' is assigned a value but never used  
'merge' is not defined
Module build failed: SyntaxError: "Pagination" is read-only
```

I tried working around these wish various kludges but didn't get anywhere, do you have any suggestions for what is wrong in my environment?

Also, another quick question. Would it be possible to use the uncompiled template.js in the merge so we don't have to manipulate the compiled output, no worries if this is not possible.

**Comment by matfish2** [comment]
You need to install the `merge` npm package
`Pagination` never used: Did you include it in your `components` objects?
read-only: I don't know

You can modify the uncompiled template and use the `vue-jsx-transform` to compile it. Then merge your compiled file.

**Comment by matfish2** [comment]
The plugin now supports themes. You can pass it an object like the one found in the themes folder.
