### ISSUE TITLE
Allow change styles of First, Prev, Next, Last buttons

### ISSUE THREAD

**Issue by izundo-viennv** [matfish2/vue-pagination-2#17]
I found that the library doesn't have any options for changing First, Prev, Next, Last buttons and can't click First and Last buttons as well

**Comment by matfish2** [comment]
First and last buttons were not introduced up until a few days ago, The double arrows represent chunks navigation. I will add the ability to change the text of those buttons.

**Comment by Zhythero** [comment]
I do think it would be preferable to put the content inside those buttons into slots instead of props.

**Comment by matfish2** [comment]
I wasn't planning on new props. I was going to put it in `options.texts` Seems like an over-complication to use slots, as I don't think HTML would be necessary

**Comment by Zhythero** [comment]
How about when font libraries such as ionicons or font-awesome are preferred?

**Comment by matfish2** [comment]
I have made the component renderless since version 2.0, which means you can quite easily create your own template now, with the HTML structure that suits you.
https://github.com/matfish2/vue-pagination-2#custom-template
