### ISSUE TITLE
destroy hook does not work when event bus is not in use.

### ISSUE THREAD

**Issue by woodhull** [matfish2/vue-pagination-2#19]
- Vue.js version: 2.5.13
- consumed using: webpack
- FULL error message (including stack trace):

TypeError: bus.$off is not a function
    at VueComponent.beforeDestroy (Pagination.js:180)
    at callHook (vue.esm.js:2895)
    at VueComponent.Vue.$destroy (vue.esm.js:2677)
    at destroy (vue.esm.js:4110)
    at invokeDestroyHook (vue.esm.js:5647)
    at invokeDestroyHook (vue.esm.js:5652)
    at VueComponent.patch [as __patch__] (vue.esm.js:5985)
    at VueComponent.Vue.$destroy (vue.esm.js:2700)
    at destroy (vue.esm.js:4110)
    at invokeDestroyHook (vue.esm.js:5647)
logError @ vue.esm.js:1717
globalHandleError @ vue.esm.js:1708
handleError @ vue.esm.js:1697
callHook @ vue.esm.js:2897
Vue.$destroy @ vue.esm.js:2677
destroy @ vue.esm.js:4110
invokeDestroyHook @ vue.esm.js:5647
invokeDestroyHook @ vue.esm.js:5652
patch @ vue.esm.js:5985
Vue.$destroy @ vue.esm.js:2700
destroy @ vue.esm.js:4110
invokeDestroyHook @ vue.esm.js:5647
patch @ vue.esm.js:5985
Vue.$destroy @ vue.esm.js:2700
teardown @ index.js:3
e.dispatch @ turbolinks.js:5
r.notifyApplicationAfterVisitingLocation @ turbolinks.js:6
r.startVisit @ turbolinks.js:6
r.startVisitToLocationWithAction @ turbolinks.js:5
r.visitProposedToLocationWithAction @ turbolinks.js:5
r.visit @ turbolinks.js:5
r.clickBubbled @ turbolinks.js:6
(anonymous) @ turbolinks.js:5

- relevant code
The destroy hook does not work if you're not using the event bus.

**Comment by matfish2** [comment]
The event bus is called internally, and is not dependent upon the user importing it to his own project.
I see you are using `turbolinks`. Are you calling `$destroy` explicitly? When?
I need to see your code.
