### ISSUE TITLE
Use of nav tag

### ISSUE THREAD

**Issue by jsodeman** [matfish2/vue-pagination-2#23]
One of the changes from vue-pagination to vue-pagination-2 is the use of a `<nav>` tag instead of a `<div>` tag. I'm using vue-tables-2 in a project with the MaterializeCSS framework, which defines a lot of styles for the <nav> tag resulting in broken pagination styling.

Resetting the styling is turning out to be complex so I'm looking for a way to change the element back into a div. All I can think of is forking vue-pagination-2 and changing it, then forking vue-tables-2 to use my pagination fork but that seems like a lot of effort for a small change.

**Comment by matfish2** [comment]
Unfortunately, at the moment `vue-pagination-2` (and consequently `vue-tables-2`) doesn't support a custom pagination template. In the near future I intend to allow the user to use a custom paginator.

**Comment by jsodeman** [comment]
Great, look forward to it.

**Comment by matfish2** [comment]
https://github.com/matfish2/vue-pagination-2#custom-template
