### ISSUE TITLE
Allow the possibility to change the elements position (text and buttons)

### ISSUE THREAD

**Issue by emersoncpaz** [matfish2/vue-pagination-2#25]
Is it possible to apply slots in pagination?

**Comment by dangthinh104** [comment]
In your vue file:
`  <pagination  ref="table"  @paginate="setPagePagination" > </pagination>`
In your script:
`  this.$refs.table.setPage(1);`

**Comment by matfish2** [comment]
https://github.com/matfish2/vue-pagination-2#custom-template
