### ISSUE TITLE
Updating RECORDS prop

### ISSUE THREAD

**Issue by theoarena** [matfish2/vue-pagination-2#26]
- Vue.js version: 2.x

Hi,
what's the best way to set/update the **RECORDS** prop dynamically?
I'm using a server side Vue-table 2 setup. All my database logic is on PHP, so i'd like to update
the pagination records count in real time.

HTML:
`<pagination :records="100" (...)`

In my pagination component declaration. Does it works?
`methods: {
setTotal: function(value){        
        this.records = value;
    }
}
`

i've also declared:
`data: {
    page: 1,
    records: 30
  },`

But with no success.

Thanks in advance!

**Comment by matfish2** [comment]
Why would the `records` prop update if you hardcode 100?

Try:
```vue
<pagination :records="records" (...)
```

**Comment by theoarena** [comment]
Yeah, that worked, thanks!!!
