### ISSUE TITLE
Error using (with) in strict mode

### ISSUE THREAD

**Issue by elithecho** [matfish2/vue-pagination-2#29]
- Vue.js version: 2.5.13
- consumed using: webpack 3 (webpacker rails) 
- FULL error message (including stack trace):

```
ERROR in ./node_modules/vue-pagination-2/compiled/Pagination.js
Module parse failed: 'with' in strict mode (14:8)
You may need an appropriate loader to handle this file type.
|    components: { RenderlessPagination: _RenderlessPagination2.default },
|    render: function render() {
|         with(this) {
|             return _c('RenderlessPagination', {
|                on: {
  @ ./node_modules/vue-pagination-2/compiled/main.js 8:18-41
|  @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/javascript/pages/ListingsPage/index.vue
@ ./app/javascript/pages/ListingsPage/index.vue
@ ./app/javascript/packs/frontend/listings.js
@ multi (webpack)-dev-server/client?http://localhost:3035 webpack/hot/dev-server ./app/javascript/packs/frontend/listings.js
webpack: Failed to compile.
```

**Comment by ATselikovSnp** [comment]
You can fix it by changing version from 2.0.0 to "vue-pagination-2": "^1.6.2" in package.json.

**Comment by elithecho** [comment]
@ATselikovSnp yeah I'd like that but I would want to use 2.0 with page props

**Comment by matfish2** [comment]
the problem is that vue compiles the template using `with` which is deprecated in strict mode. I need to find a way around it. I think for now I will unpublish 2.0

**Comment by JensvdHeydt** [comment]
Any news on this subject? I need to use the new page prop feature.

**Comment by matfish2** [comment]
I've just published a new version (2.0.3), in which I adopted the "controlled component" approach; i.e the pagination component no longer saves the state (current page) but rather keeps it in sync with the value passed by the consumer, using `v-model`. @JensvdHeydt, @choonggg, Can you please give it a go and let me know your findings?

For instructions, please use the `npm` readme file, or switch to the "controlled-component" branch.

**Comment by elithecho** [comment]
hey @matfish2 so sorry come back this late, just tested and it's working fine with the controlled component. Thanks! 👍

**Comment by matfish2** [comment]
Updated package to work without `with` keyword.
