### ISSUE TITLE
Programmatic Manipulation

### ISSUE THREAD

**Issue by paulheijman** [matfish2/vue-pagination-2#31]
- Vue.js version: 2.5.9
- consumed using: CDN
- FULL error message (including stack trace): "setPage is not a function"
- relevant code: https://jsfiddle.net/gv309mwj/

Probably some mistake on my part, but I can't figure out why it isn't working...
Any help is welcome!

**Comment by matfish2** [comment]
Apparently making the component renderless (i.e allowing the consumer to create his own template) had the side-effect of pushing the component one level down. So instead of:
```
this.$refs.foobar.setPage(1)
```
try
```
this.$refs.foobar.$children[0].setPage(1)
```
I will try and find a more elegant solution
