### ISSUE TITLE
Example code missing :page prop

### ISSUE THREAD

**Issue by kerrsmith** [matfish2/vue-pagination-2#33]
If you add the the following line of code as shown in the example:

<pagination :records="500" @paginate="myCallback"></pagination>

you get the following error:

[Vue warn]: Missing required prop: "page"

The example line needs to read:

<pagination :page=1 :records="500" @paginate="myCallback"></pagination>

Once the :page prop is added the code works as expected - this change to the README.md code would make it work straight away for new users.

**Comment by matfish2** [comment]
Thanks. I've updated the README and the package (the prop is now a v-model)
