### ISSUE TITLE
:page and :records do not have default values

### ISSUE THREAD

**Issue by kerrsmith** [matfish2/vue-pagination-2#34]
If you run the code when :page and :records do not have values they do not get a default and you get the following errors:

[Vue warn]: Invalid prop: type check failed for prop "page". Expected Number with value NaN, got Undefined
 
and

[Vue warn]: Invalid prop: type check failed for prop "records". Expected Number with value NaN, got Undefined

The :per-page prop does not have this issue and correctly gets a default value of 25.

For example my code uses Laravel paginate to get the required props data (stored in a tasks object) but if you do the following, when the page initially runs this data does not exist and you get the errors above:

<pagination :page="tasks.current_page" :per-page="tasks.per_page" :records="tasks.total" @paginate="getData" />

Currently you need to add the ternary operator to give these two props default values:

<pagination :page="(tasks.current_page) ? tasks.current_page : 1" :per-page="tasks.per_page" :records="(tasks.total) ? tasks.total : 1" @paginate="getData" />

**Comment by matfish2** [comment]
Those are required values by design. You must pass the model for the page and the number of records (there is no sense in setting an arbitrary number of records)
