### ISSUE TITLE
Documentation not clear enough

### ISSUE THREAD

**Issue by gabrielbuzziv** [matfish2/vue-pagination-2#4]
- Vue.js version: 2.0.1
- consumed using: webpack

> Programmatic Manipulation
> 
> To programmatically set the page apply a ref identifier to the component and use one of the following methods:
> 
> setPage(page)
> next()
> prev()
> nextChunk()
> prevChunk()
> All methods return true if the page is legal and was thus set, or false otherwise.

where should i adjust the method setPage for example, i added in my component and nothing happens. Maybe the documentation is not clear enough, you could create a kind of example =D

For example
```
methods: {
            setPage (page) {
                alert('settingpage')
            },
}
```

**Comment by matfish2** [comment]
These are not methods that you define. They are predefined by myself, and you can _call_ them on the component.
Read about "ref" in `vue`'s documentation.
The docs are clear enough. They are not supposed to teach you how to use `vue`.

**Comment by gabrielbuzziv** [comment]
Ok, but how i will be able to load again the next page items if the paginator don't know what action need to be executed?

to use this paginator i'm supposed to have all my list already in the store?

**Comment by matfish2** [comment]
The paginator is content-agnostic, i.e it does not know anything about your list, table or what have you.
Its sole purpose is to detect (or trigger) page selection. 
It is completely up to the consumer to decide what to do with this event. 
Have a look at version 1 [demo](https://jsfiddle.net/matfish2/rnw8jjs3/) to better understand the concept.

**Comment by gabrielbuzziv** [comment]
@matfish2 thanks, now i got it, haha sorry for the inconvenience, i'm still learning vue and vuex 2 =D
