### ISSUE TITLE
RenderlessPagination missing from build when using custom template

### ISSUE THREAD

**Issue by mrsweaters** [matfish2/vue-pagination-2#42]
When trying to use the custom template option I realized that a new build has not been released that has the RenderlessPagination component.  Works fine when referencing master. Can you push out a new release?

```
import RenderlessPagination from 'vue-pagination-2/compiled/RenderlessPagination.js';
```

**Comment by matfish2** [comment]
Pushed to npm (v2.0.1)

**Comment by matfish2** [comment]
I've reverted to 2.0.3 because of issues with the `with` keyword in strict mode
