### ISSUE TITLE
[meta] Version 2.0.3 not on npmjs.org

### ISSUE THREAD

**Issue by cmitz** [matfish2/vue-pagination-2#44]
- Vue.js version: 2.6
- consumed using: Webpack
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

The steps above are not really relevant. I tried vue-table-2 and noticed `with(this)` bug #29 and it seems to have been fixed in v2.0.3. However, v2.0.3 is not on npmjs, resulting in vue-tables-2 throwing this error in my project.

What was the reason for unpublishing 2.0.3? It is still listed, but not as `latest` version

**Comment by matfish2** [comment]
I was trying to fix #42 and got myself in trouble. For some reason, I can't find 2.0.3 on master, Also can't unpublish 2.0.1. Trying to resolve. In the meantime, I will force 2.0.3 on vue-tables-2

**Comment by cmitz** [comment]
Okay, I already monkeypatched `v2.0.3` into my `yarn.lock` and that worked 🙈 
Thanks for the quick reply

**Comment by matfish2** [comment]
Upgraded package to new version. Also reflected in vue-tables-2 reference
