### ISSUE TITLE
bug, if total pages is 4 and chunks is 10, hasEdgeNav can never be true, first and last links do not render

### ISSUE THREAD

**Issue by iambumblehead** [matfish2/vue-pagination-2#47]
- Vue.js version: 2.6.11
- consumed using: webpack

```vue
<template>
    <VuePagination2
        v-bind="$attrs"
        class="input-pagination"
        :records="records"
        :page="page"
        :per-page="10"
        :options="{
            edgeNavigation: true,
            texts: {
                count: $t( 'inputPagination.showingNRecords' ),
                first: $t( 'inputPagination.first' ),
                last: $t( 'inputPagination.last' )
            }
        }"
        @paginate="$emit( 'paginate', $event )"
        @input="$emit( 'input', $event )"
    />
</template>
```

**Comment by iambumblehead** [comment]
[this seems like a bug][0] --if total pages is `4` and chunks is `10`, [`hasEdgeNav` can never be true][1] and the first last text will not be rendred.

[0]: https://github.com/matfish2/vue-pagination-2/blob/master/src/RenderlessPagination.js#L153-L155
[1]: https://github.com/matfish2/vue-pagination-2/blob/master/src/RenderlessPagination.js#L30

**Comment by matfish2** [comment]
Why is it a bug? You are not supposed to see first and last if they are not relevant
