### ISSUE TITLE
Why are custom methods not called by @paginate

### ISSUE THREAD

**Issue by bigger-xu** [matfish2/vue-pagination-2#55]
- Vue.js version: 2.5.2
- consumed using: webpack
- FULL error message (including stack trace):There is no error message
- relevant code:
- steps for reproducing the issue:

`<pagination :records="100" :per-page="10" @paginate="getContentPage" v-model="page" :options="options"></pagination>`
`methods: {
    getContentPage(){
      console.log(this.page)
    }
  }`

**Comment by BvdMerwe** [comment]
Having the same behaviour on my end.

it was changed to the **input** event in this commit 71e4312fe7948fafbdbf50c9730062a1b7772632

**Comment by bigger-xu** [comment]
help me!!!!! I'm going crazy!!!!!!

**Comment by BvdMerwe** [comment]
instead of using @paginate, instead use @input like so
`<pagination :records="100" :per-page="10" @input="getContentPage" v-model="page" :options="options"></pagination>`

I'm not sure if this is the intended behaviour or if it will change.

**Comment by bigger-xu** [comment]
Thank you very much. @Input solved my problem  Thank you

**Comment by swaprenge** [comment]
> instead of using @paginate, instead use @input like so
> `<pagination :records="100" :per-page="10" @input="getContentPage" v-model="page" :options="options"></pagination>`
> 
> I'm not sure if this is the intended behaviour or if it will change.

`@input` solved my problem too. But I am getting this error 

`[Vue warn]: Invalid prop: custom validator check failed for prop "value".
found in
<Pagination>`

**Comment by matfish2** [comment]
Fixed. @swaprenge your issue seems to be different. If validation fails it means that the model is either not numeric (e.g "1" instead of 1) or less than 1. You can examine the value in chrome dev tools and find the reason.
