### ISSUE TITLE
It does not display "0 records" when passing an array with 0 results

### ISSUE THREAD

**Issue by AllanOricil** [matfish2/vue-pagination-2#59]
When passing 0 records, the paginator does not show "0 records".

**Comment by matfish2** [comment]
As it should

**Comment by AllanOricil** [comment]
I had a use case where I had to show 0 records. To achieve that I had to treat it as an exception, which required me to write extra lines of html. I think it makes sense for you to implement it, as it would not require the developer to handle it separatly.

it would go from this:

if 0 records
my extra html lines
else
your paginator

to this:

your paginator
