### ISSUE TITLE
Update Merge Dependency to 2.1.1

### ISSUE THREAD

**Issue by ghost** [matfish2/vue-pagination-2#63]
- Vue.js version: 2.6.12
- consumed using: webpack
- FULL error message (including stack trace):
```
merge  <2.1.1
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1666
No fix available
node_modules/merge
  vue-pagination-2  0.1.6 - 0.3.1 || >=1.5.0
  Depends on vulnerable versions of merge
  node_modules/vue-pagination-2
    vue-tables-2  *
    Depends on vulnerable versions of merge
    Depends on vulnerable versions of vue-pagination-2
    node_modules/vue-tables-2
```
- relevant code: N/A
- steps for reproducing the issue: npm (install/update)

Client won't allow any packages with vulnerabilities in production code.

Please update merge to v2.1.1

Thank you.

**Comment by matfish2** [comment]
Done. v3.0.9

**Comment by ghost** [comment]
Thanks, much appreciated.

**Comment by ghost** [comment]
Sorry to be a pain, but this also needs to be done in `vue-tables-2` which still uses merge 1.2.0

I should have opened this issue there and referenced pagination in that issue.

**Comment by retosteffen** [comment]
And in the vue3 branch! That would be awesome!

**Comment by matfish2** [comment]
Sorry, I've updated `vue-tables-2` public repo, forgot the private :) Updated both vue2 and vue3 on private repo (v2,2,4 and 0.3.8 respectively)

**Comment by retosteffen** [comment]
I meant https://github.com/matfish2/vue-pagination-2/tree/vue3 :) But great job!

**Comment by matfish2** [comment]
Thanks @retosteffen, too many repos... Updated vue3 branch. v0.1.3

**Comment by retosteffen** [comment]
Perfect! Thanks!!
I completely understand about too many repos :)
