### ISSUE TITLE
how do I provide a custom theme?

### ISSUE THREAD

**Issue by jmartsch** [matfish2/vue-pagination-2#65]
- Vue.js version: 3.
- consumed using: vite
I want to use a custom theme which uses tailwindcss classes. How would I do that?

BTW: nice component :)

**Comment by matfish2** [comment]
Currently no support for custom theme, but you can use custom template instead: https://www.npmjs.com/package/v-pagination-3#custom-template

**Comment by jmartsch** [comment]
Thanks. That's what I already did. An option for custom themes would be nice. I think tailwind is pretty popular right now.

**Comment by matfish2** [comment]
Sorry, forgot my own code.... It's possible to pass a custom theme. Just pass an object, rather than a string, to the `theme` option (`options.theme`):

e.g Bootstrap 3:

```js
 {
    nav:'',
    count:'',
    wrapper:'',
    list:'pagination',
    item:'page-item',
    link:'page-link',
    next:'',
    prev:'',
    active:'active',
    disabled:'disabled'
}
```
