### ISSUE TITLE
Bulma theme focus error on pagination changes

### ISSUE THREAD

**Issue by artemverbo** [matfish2/vue-pagination-2#67]
Hi! Having a minor issue with error thrown every time pagination is changed with Bulma theme (where active class is different from 'active')

```Cannot read property 'focus' of null```

The issue seems to be simply here, where active class if hardcoded:
`this.$el.querySelector('li.active a').focus();`
https://github.com/matfish2/vue-pagination-2/blob/fdfa79aa246041c8974017adfd8ce99e03dd53c5/src/RenderlessPagination.js#L216

Thank you!

**Comment by matfish2** [comment]
Thanks for reporting. Fixed in 3.0.91
