### ISSUE TITLE
uncaught (in promise) RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ZtheLeader** [matfish2/vue-pagination-2#68]
- Vue.js version: 3.0 with Typescript
- consumed using: (browserify/webpack): webpack/ VueCLI 3.0

Whenever I try to render the component following errors appear and component does not render:

![image](https://user-images.githubusercontent.com/26215607/121439233-f22d4180-c99e-11eb-9dbd-33fa3e89c355.png)

**Comment by matfish2** [comment]
Hard to say without seeing the code you are using, but it seems like your code is infinitely replicating the pagination component. Is it embedded in a `v-for`?
