### ISSUE TITLE
Uncaught (in promise) RangeError: Invalid array length with scroll option

### ISSUE THREAD

**Issue by mrfox1** [matfish2/vue-pagination-2#69]
- Vue.js version: 3.0 js
- consumed using: (browserify/webpack) webpack/ VueCLI 3.0
- when i try to add `chunksNavigation: "scroll"` to options following errors appear and component does not render:
![Screenshot from 2021-06-11 13-05-49](https://user-images.githubusercontent.com/12751091/121670667-5db60280-cab6-11eb-8cba-60770fb943db.png)

**Comment by matfish2** [comment]
Note to self. Reproduction link: https://codesandbox.io/s/v-pagination-3-scroll-848ux?file=/src/App.vue

**Comment by matfish2** [comment]
Fixed in 0.1.6
