### ISSUE TITLE
any example?

### ISSUE THREAD

**Issue by g0ld3lux** [matfish2/vue-pagination-2#7]
i manage to install everything , and render...
but i cant manage to show the data i want to be paginated...
documentation lack info i hope you can give more insights on this thanks

**Comment by matfish2** [comment]
> i cant manage to show the data i want to be paginated..

What did you try? The docs are very clear as to how a page selection should be handled.
The pagination component has no knowledge of your data. Its only job is to fire an event with the page number. All the rest is up to you.
