### ISSUE TITLE
Options do not seem to work

### ISSUE THREAD

**Issue by Marchiuzzz** [matfish2/vue-pagination-2#71]
Hi, I'm not sure if I'm doing something wrong but I want to add "first" and "last" options but even when I specify this option in options prop they do not appear

![image](https://user-images.githubusercontent.com/73941456/122523380-a1ad8800-d01f-11eb-8f42-c3be348302c3.png)

- Vue.js version: 2.6.12
- consumed using: webpack
- FULL error message (including stack trace): none
- relevant code: `<pagination class="w-100 d-flex justify-content-center text-center" :options="{edgeNavigation: true}" :key="filteredObjectsLength" :records="filteredObjectsLength" v-model="page" :per-page="50"/>`

**Comment by matfish2** [comment]
First and Last only appear when there is more than one chunk
