### ISSUE TITLE
Place A Part Of Pagination Element in The Left Side

### ISSUE THREAD

**Issue by saadabdurrazaq** [matfish2/vue-pagination-2#72]
Hi, I got some difficult. I am not able to place this element in the left side. Can you please help with the solution? I use https://www.npmjs.com/package/v-pagination-3
![pag](https://user-images.githubusercontent.com/15057404/122898984-95a22d00-d375-11eb-9cfb-0d0574e7a252.png)

**Comment by matfish2** [comment]
You can use a custom template to change the HTML:
https://github.com/matfish2/vue-pagination-2#custom-template
