### ISSUE TITLE
Vue received a Component which was made a reactive object

### ISSUE THREAD

**Issue by ahmedgadit** [matfish2/vue-pagination-2#73]
main.js?id=cb69ded19574dcd228d5:5871 [Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 
Component that was made reactive:

- Vue.js version: 3.0.5
- consumed using: (browserify/webpack) "webpack": "^5.25.1"
- FULL error message (including stack trace):
main.js?id=cb69ded19574dcd228d5:5871 [Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 
Component that was made reactive:
 at <RenderlessPagination ref="pg" > 
  at <Pagination modelValue=1 onUpdate:modelValue=fn options= {template: {…}, chunksNavigation: false}chunksNavigation: falsetemplate: {name: "Pagination", emits: Array(2), props: Array(1), __file: "resources/frontendjs/components/Pagination.vue", render: ƒ, …}__proto__: Object  ... > 
  at <Products onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

- relevant code:

` <pagination v-model="page" :options="options" :records="500" :per-page="25" @paginate="myCallback" ref="custPagination"/>`

```
import MyPagination from './../../components/Pagination'
export default {
    data() {
        return {
            options: {
                template: MyPagination,
                chunksNavigation: false,
            },
            page:1,
```

**Custom Pagination** 

```
<template>
    <div class='pagination-wrap text-right'>
            <ul v-show="props.showPagination">

                <li v-if="props.hasEdgeNav" :class='props.theme.firstPage' @click="props.setFirstPage">
                    <button type="button" v-bind="props.firstPageProps">{{props.texts.first}}</button>
                </li>

                <li v-if="props.hasChunksNav" :class='props.theme.prevChunk' @click="props.setPrevChunk">
                    <button type="button" v-bind="props.prevChunkProps">{{props.texts.prevChunk}}</button>
                </li>

                <li :class="props.theme.prev" @click="props.setPrevPage">
                    <a type="button" v-bind="props.prevProps"><span class="fa fa-long-arrow-left"></span></a>
                </li>

                <li v-for="page in props.pages" :key="page" :class="props.pageClasses(page)"
                    v-on="props.pageEvents(page)">
                    <a type="button" v-bind="props.aProps">{{page}}</a>
                </li>

                <li :class="props.theme.next" @click="props.setNextPage">
                    <a type="button" v-bind="props.nextProps"><span class="fa fa-long-arrow-right"></span> </a>
                </li>

                <li v-if="props.hasChunksNav" :class='props.theme.nextChunk' @click="props.setNextChunk">
                    <button type="button" v-bind="props.nextChunkProps">{{props.texts.nextChunk}}</button>
                </li>

                <li v-if="props.hasEdgeNav" :class="props.theme.lastPage" @click="props.setLastPage">
                    <button type="button" v-bind="props.lastPageProps">{{props.texts.last}}</button>
                </li>

            </ul>
            <p v-show="props.hasRecords" :class='props.theme.count'>{{props.count}}</p>

    </div>

</template>

<script>
    export default {
        name: 'Pagination',
     emits: ['update:modelValue', 'paginate'],
        props: ['props']
    }
</script>
```

- steps for reproducing the issue:

**Comment by matfish2** [comment]
use `markRaw`:

```
import {markRaw} from 'vue'
...
 template: markRaw(MyPagination),
```
