### ISSUE TITLE
How to Get Index in This Package?

### ISSUE THREAD

**Issue by saadabdurrazaq** [matfish2/vue-pagination-2#74]
I'm trying pagination in this package with below code

    users.indexOf(user) + 1

my quetion is how can get index in pagination?

for example :
I have data in paging or page one :<br>

> index :"1" - Kathy Sparks
>
> index :"2" - Gladys Tate 

and then if I'm click paging two, I want to index continue

> index : 3 - Shannon 
>
> index : 4 - Rosetta Scott

Instead of index 1 and index 2 again.

**Comment by matfish2** [comment]
This is not the responsibility of the package. The package allows the user to select a page. From there (using the page prop you passed to `v-model`) you can easily calculate the range of records for the given page
