### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Makogai** [matfish2/vue-pagination-2#77]
How can you customize the template? The documentation is confusing and doesn't show what to put where.

**Comment by matfish2** [comment]
1. Copy https://github.com/matfish2/vue-pagination-2/blob/master/src/Pagination.vue to your own `MyPagination.vue` file. (If you are using the vue3 version copy from the `vue3` branch instead)
2. Modify to your needs.
3. Tell the plugin to use your template instead of the default:
```js
import MyPagination from './MyPagination'
...
{
    options: {
        template: MyPagination    
    }   
}
```
