### ISSUE TITLE
How to use this in laravel?

### ISSUE THREAD

**Issue by AkhtarHussain312** [matfish2/vue-pagination-2#78]
- Vue.js version:
- consumed using: (browserify/webpack)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

**Comment by UXandre** [comment]
Was wondering if you've got any good guideline for using this package with Laravel 8? @AkhtarHussain312

**Comment by matfish2** [comment]
This is a client side package, which means it is server agnostic. Its only responsibility is to allow the user to select a page and update the state accordingly. To listen for a page select event you can either add a watcher on the `page` property of your data (or whatever you named the property passed the `v-model`, or listen to the `paginate` event on the component. In the callback you pass the selected page to the ajax call, return the relevant data from the server, and assign to your reactive state . E.g:

```js
watch:{
async page() {
  const {data} = await axios.get(`/data?page=${this.page}')
  this.data = data
  }
}
```

**Comment by UXandre** [comment]
I've made it work by sending axios requests through the Callback function. The only thing that I don't understand is that how the Pagination works correctly without me returning the response?

**Comment by matfish2** [comment]
The package modifies the model you pass to `v-model` when a user selects a page, thus syncing the UI and the client-side state (Vue's awesomeness makes it work both ways, So if you programmatically change the model the view will render itself accordingly). The developer can then use this state to reflect the current page in whatever way fits the app. From your response I understand that you already did it, which is great :) Long story short, the package offers a reactive self-contained VM (View Model), which exposes itself to your application.

**Comment by UXandre** [comment]
Thanks @matfish2 Very helpful!
