### ISSUE TITLE
Cursor 'Pointer' CSS Not Applied Consistently

### ISSUE THREAD

**Issue by jwbats** [matfish2/vue-pagination-2#80]
- Vue.js version: 3.0.91
- consumed using: WebPack
- FULL error message: N/A
- relevant code: N/A
- steps for reproducing the issue: use paginator on page that has Bootstrap 4 on it

I'm using this paginator on a page that's powered by Bootstrap 4.

For the numbered buttons (1, 2, 3, etc.), it will automatically apply a cursor 'pointer' styling, because they have 'a' tags with the role="button" attribute.

For the prev/next buttons (<<, <, >, >>) it will not do that, because 'a' elements do not have the role="button" attribute.

Both numbered and prev/next buttons, are all clickable elements. It would be nice if they were all styled to have cursor 'pointer' by default, rather than only some of them getting that via Bootstrap 4.

**Comment by jwbats** [comment]
I've temporarily solved it by adding this to my parent component:

```
/deep/ .VuePagination a.page-link {
    cursor:pointer;
}
```

**Comment by matfish2** [comment]
`a` tags were replaced with `button` elements, so this is resolved

**Comment by jwbats** [comment]
When will the new version be available on npmjs?

**Comment by matfish2** [comment]
It is already available https://www.npmjs.com/package/v-pagination-3

**Comment by jwbats** [comment]
That's another package and it's for Vue 3.

I'm using Vue 2 and have created this issue under the [vue-pagination-2 repo](https://github.com/matfish2/vue-pagination-2), where the [vue-pagination-2 npm page](https://www.npmjs.com/package/vue-pagination-2) (currently still 3.0.91) points to.

**Comment by matfish2** [comment]
You wrote "Vue.js version: 3.0.91", I suppose you meant vue-pagination version. I will have to change on the vue2 (master) branch. Reopening for now

**Comment by jwbats** [comment]
Ah, sorry... my bad. Indeed I did mean that.

Although, in my defense... it's because that's the default template that 'new issue' will show you in this repo. That should probably explicitly read 'vue2 version'. And it should probably also request the 'vue-pagination-2' version.

That would clear things up.

Anyway, tnx for fixing.
