### ISSUE TITLE
Paginator texts can't be disabled

### ISSUE THREAD

**Issue by tonila** [matfish2/vue-pagination-2#83]
- Vue.js version: 3.0.11
- consumed using: webpack

It would be nice if paginator texts could be disabled eg. by setting options.texts to null.

Best I could do was to set options.texts.count to '', witch was kinda hacky.

```
<pagination
  v-if="productData.total"
  :model-value="productData.current_page"
  :records="productData.total"
  :per-page="productData.per_page"
  :options="{
    chunk: 10,
    texts: {
      count: ''
    }
  }"
  @update:modelValue="onPageChange"
/>
```

**Comment by Saibamen** [comment]
+1 for this feature

**Comment by matfish2** [comment]
Added `hideCount` option to v-pagiantion-3 0.1.7
