### ISSUE TITLE
How can i have a module with multiple paginations?

### ISSUE THREAD

**Issue by gabrielbuzziv** [matfish2/vue-pagination-2#9]
Is not really a issue, but a doubt using this package.
I have a module that can have two paginations, how can i deal with it?

**Comment by matfish2** [comment]
The required `for` prop uniquely identifies every component. Simply create two components with different identifiers. Then listen to the corresponding events and act accordingly. E.g:

```html
<pagination for="first" :records="500"></pagination>
<pagination for="second" :records="500"></pagination>
```

```js
VueEvent.$on('vue-pagination::first', function(page) {
      // display the relevant records using the page param
  });

VueEvent.$on('vue-pagination::second', function(page) {
      // display the relevant records using the page param
  });
```
